### PR TITLE
Policheck update - Sept 6 | Bulk Update

### PR DESCRIPTION
**Pull request by MeeraDi**
This bulk PR addresses the terms "country" and "countries" identified by Policheck as potentially sensitive terms in the following bugs:

- https://dev.azure.com/msft-skilling/learn-platform-policheck/_queries/edit/148674
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_queries/edit/137616

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/locale/time-zones.md](https://github.com/MicrosoftDocs/globalization/blob/748857e5c2bedd0d26b1ea961907941621e9450f/globalization%2Flocale%2Ftime-zones.md) | 88 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d3812dc-67b7-4cad-93f3-b653dd4c545a) | [:white_check_mark:](# "Successfully processed") |
| [globalization/localizability/images-and-icons.md](https://github.com/MicrosoftDocs/globalization/blob/748857e5c2bedd0d26b1ea961907941621e9450f/globalization%2Flocalizability%2Fimages-and-icons.md) | 77 | 100 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2e859dc-248c-49ab-a3b5-29303c5b9682) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by MeeraDi** [comment]
@jowilco 
This PR addresses terms identified by Policheck as potentially sensitive. If you agree with these changes, please approve and merge these changes. Thanks

**Comment by jowilco** [comment]
> @jowilco This PR addresses terms identified by Policheck as potentially sensitive. If you agree with these changes, please approve and merge these changes. Thanks

@MeeraDi I believe that all of these instances were using "country" correctly. In all three cases, the use of "country" is very specific and nuanced. Please can you explain why you feel that adding "/region" would avoid the country/region sensitivity issue in these three cases? The only one that I might change is "Even when a country’s width would suggest that more than one time zone would be used, countries might elect to use fewer time zones. For example, China..."
As the example is for China, which is definitely a country, we could reword as "... would be used, the country might..."

**Comment by MeeraDi** [comment]
Hello @jowilco 
To eliminate future risk, Policheck includes all instances where the terms "country" and "countries" appear. However, as you mentioned these instances sometimes need to be retained in specific cases, in these cases we can prevent Policheck from continuing to report on them. I am happy to revert any inappropriate changes and update the Policheck issue to skip them in future runs.

**Comment by jowilco** [comment]
Thanks @MeeraDi  - Yes, please can this PR be closed, and skip the check for these specific instances in future runs.

Note that Policheck has identified valid issues previously, so we do appreciate the checking!

**Pull request closed without merging**
