### PR TITLE
updated meta description

### PR DESCRIPTION
**Pull request by Khairunj**

### CODE REVIEW

**Comment by Khairunj** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/globalization, working directory: W:\g421-s, target branch: live, target branch commit: f053f361c8e61f07fbad31cdef39d1e4a91f76bb, source branch: master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C26%5C7e74dcc8-0c29-2d83-8948-de96dd917559%5CPullRequest%5C201708260606517359-34%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Khairunj** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/globalization, working directory: W:\zund-s, target branch: live, target branch commit: f053f361c8e61f07fbad31cdef39d1e4a91f76bb, source branch: master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C28%5C7e74dcc8-0c29-2d83-8948-de96dd917559%5CPullRequest%5C201708281348435715-34%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Khairunj** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/globalization, working directory: W:\4zb0-s, target branch: live, target branch commit: f053f361c8e61f07fbad31cdef39d1e4a91f76bb, source branch: master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C28%5C7e74dcc8-0c29-2d83-8948-de96dd917559%5CPullRequest%5C201708281349107839-34%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Khairunj** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/globalization, working directory: W:\sz0c-s, target branch: live, target branch commit: f053f361c8e61f07fbad31cdef39d1e4a91f76bb, source branch: master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C28%5C7e74dcc8-0c29-2d83-8948-de96dd917559%5CPullRequest%5C201708281349507664-34%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Khairunj** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/globalization, working directory: W:\rkzw-s, target branch: live, target branch commit: f053f361c8e61f07fbad31cdef39d1e4a91f76bb, source branch: master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C28%5C7e74dcc8-0c29-2d83-8948-de96dd917559%5CPullRequest%5C201708281351185218-34%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Khairunj** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/globalization, working directory: W:\rxm2-s, target branch: live, target branch commit: 6b28d9419787db09f7b2a28c07cfdc587f589f74, source branch: master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C7%5C7e74dcc8-0c29-2d83-8948-de96dd917559%5CPullRequest%5C201709071504473603-34%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Khairunj** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/globalization, working directory: W:\shsz-s, target branch: live, target branch commit: 53c97f5e11a5a59fe6aeb6c2c71f028aa6f608cf, source branch: master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C22%5C7e74dcc8-0c29-2d83-8948-de96dd917559%5CPullRequest%5C201709221522145293-34%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6jnf32Vaq6ufGyapvVHY5sW33vFz73P3lzbqXftcHDI%3D&st=2017-09-22T15%3A17%3A27Z&se=2017-09-23T15%3A27%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-kents** [comment]
closing to see if this cleans tihngs up

**Pull request closed without merging**
