### PR TITLE
Update link to Multilingual App Toolkit

### PR DESCRIPTION
**Pull request by fitojb**
The previous link didn’t lead anywhere anymore. Let me know if there is a better link than this and I’ll amend the patch.

### CODE REVIEW

**Comment by fitojb** [comment]
Ping?

**Comment by GwynethM** [comment]
Google returns https://developer.microsoft.com/en-us/windows/develop/multilingual-app-toolkit as a valid link.

**Comment by fitojb** [comment]
Ping?

**Comment by v-kents** [comment]
@fitojb  Sorry about the delay on accepting this. Now live.

**Pull request merged**
