### PR TITLE
Master

### PR DESCRIPTION
**Pull request by v-kents**

### CODE REVIEW

**Comment by Khairunj** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[globalization/toc.yml](https://github.com/v-kents/globalization/blob/master/globalization/toc.yml) | :x:Error | | [Details](#user-content-globalization%2Ftoc.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="globalization%2Ftoc.yml"></a>
### [globalization/toc.yml](https://github.com/v-kents/globalization/blob/master/globalization/toc.yml)
 - **[Error]** W:\yr0r-s\globalization\toc.yml is not a valid TOC File: W:\yr0r-s\globalization\toc.yml is not a valid TOC file.
 - **[Error]** W:\yr0r-s\globalization\toc.yml is not a valid TOC File: W:\yr0r-s\globalization\toc.yml is not a valid TOC file.
 - **[Error]** Unable to load file: toc.yml via processor: ExperimentalTocDocumentProcessor.
 - **[Error]** Unable to load file: toc.yml via processor: TocDocumentProcessor.

<a name=""></a>
### []()
 - **[Error]** W:\yr0r-s\globalization\toc.yml is not a valid TOC File: W:\yr0r-s\globalization\toc.yml is not a valid TOC file.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C5%5C7e74dcc8-0c29-2d83-8948-de96dd917559%5CPullRequest%5C201710052118333082-40%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aL7Gq5KudQN815ZMBgNtJQrRno8xW1oH5FAXV5kLGxc%3D&st=2017-10-05T21%3A14%3A32Z&se=2017-10-06T21%3A24%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Khairunj** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[globalization/input/font-technology.md](https://github.com/v-kents/globalization/blob/master/globalization/input/font-technology.md) | :white_check_mark:Succeeded | |
[globalization/software-internationalization.md](https://github.com/v-kents/globalization/blob/master/globalization/software-internationalization.md) | :white_check_mark:Succeeded | |
[globalization/toc.yml](https://github.com/v-kents/globalization/blob/master/globalization/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C5%5C7e74dcc8-0c29-2d83-8948-de96dd917559%5CPullRequest%5C201710052124571859-40%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7A40C69C45zgS8QCvt%2BlfCEbON0Eije8Z9BWWsuuzLY%3D&st=2017-10-05T21%3A20%3A57Z&se=2017-10-06T21%3A30%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Review by FdDaopopx — COMMENTED** [review]
Allllllll

**Comment by FdDaopopx** [comment]
> Allllllll

**Pull request merged**
