### PR TITLE
fix language ids

### PR DESCRIPTION
**Pull request by mairaw**
Testing if #53 is fixed with a new PR

This PR uses the approved language IDs for the code blocks
https://docs.microsoft.com/en-us/contribute/code-in-docs#supported-languages

### CODE REVIEW

**Comment by mairaw** [comment]
@v-kents do you know who owns this repo?

**Comment by v-kents** [comment]
@mairaw I think the last time I asked around, it was Scott Li (CELA) (not sure if he's on Github, I'll email him separately).

However, I can merge this if you'd like. It all looks clean and more correct than before.

**Comment by mairaw** [comment]
@v-kents this is a super straightforward PR so I think it should be ok to merge. But thanks for emailing the owner so they can start tracking PRs from time to time here. This doesn't seem like a busy repo.

**Comment by v-kents** [comment]
@mairaw 'struth. Ownership has also bounced around a few times due to people leaving the company. Going out now, and thank you again.

**Comment by brunolewin-msft** [comment]
@pallep - discussion about ownership of doc.microsoft.com/globalization, possibly of interest to you...

**Pull request merged**
