### PR TITLE
Policheck update - August 9 | Bulk Update

### PR DESCRIPTION
**Pull request by JustPies**
This PR addresses the following Policheck bug:

- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109053
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109055
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109058
- https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109066

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/internationalization/international-laws-and-standards.md](https://github.com/MicrosoftDocs/globalization/blob/9b8fd22ca3ce5bd1c54ea07665fac61c6abbf0e8/globalization%2Finternationalization%2Finternational-laws-and-standards.md) | 92 | 100 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9662cfd4-3336-435c-9c3e-626263a7bac6) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/other-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/9b8fd22ca3ce5bd1c54ea07665fac61c6abbf0e8/globalization%2Flocale%2Fother-locale-names.md) | 74 | 100 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/751b1c36-2d3e-41bd-a01d-bb1ab8eaaefa) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/sorting-and-string-comparison.md](https://github.com/MicrosoftDocs/globalization/blob/9b8fd22ca3ce5bd1c54ea07665fac61c6abbf0e8/globalization%2Flocale%2Fsorting-and-string-comparison.md) | 80 | 100 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70eef8bb-00a5-4839-824e-1d4ff76892f6) | [:white_check_mark:](# "Successfully processed") |
| [globalization/localizability/images-and-icons.md](https://github.com/MicrosoftDocs/globalization/blob/9b8fd22ca3ce5bd1c54ea07665fac61c6abbf0e8/globalization%2Flocalizability%2Fimages-and-icons.md) | 77 | 100 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f65e8f82-7fa2-4f97-aa19-c55738fe31ab) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/internationalization/international-laws-and-standards.md](https://github.com/MicrosoftDocs/globalization/blob/ecdade7be90176bdb00008b51efd9dd2cc55936a/globalization%2Finternationalization%2Finternational-laws-and-standards.md) | 92 | 100 | 80 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88189827-f035-4447-a92b-b2b2c5eb0330) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/other-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/ecdade7be90176bdb00008b51efd9dd2cc55936a/globalization%2Flocale%2Fother-locale-names.md) | 74 | 100 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c177ea0d-02f8-436f-83dc-bdcdbfb4547f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/sorting-and-string-comparison.md](https://github.com/MicrosoftDocs/globalization/blob/ecdade7be90176bdb00008b51efd9dd2cc55936a/globalization%2Flocale%2Fsorting-and-string-comparison.md) | 80 | 100 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15f04ed0-d0d7-4539-a1a6-e3bbf557d978) | [:white_check_mark:](# "Successfully processed") |
| [globalization/localizability/images-and-icons.md](https://github.com/MicrosoftDocs/globalization/blob/ecdade7be90176bdb00008b51efd9dd2cc55936a/globalization%2Flocalizability%2Fimages-and-icons.md) | 77 | 100 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/945cec57-6379-4d05-8859-3a05650d8802) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/internationalization/international-laws-and-standards.md](https://github.com/MicrosoftDocs/globalization/blob/76c085cb7b1f3982dc90259f00df0f9fed8dea51/globalization%2Finternationalization%2Finternational-laws-and-standards.md) | 92 | 100 | 80 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/266f039f-d3ea-4344-af48-6a5b6f8f7c4f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/other-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/76c085cb7b1f3982dc90259f00df0f9fed8dea51/globalization%2Flocale%2Fother-locale-names.md) | 74 | 100 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5f01841-295a-42d5-9dd2-e9c3d98ea19a) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/sorting-and-string-comparison.md](https://github.com/MicrosoftDocs/globalization/blob/76c085cb7b1f3982dc90259f00df0f9fed8dea51/globalization%2Flocale%2Fsorting-and-string-comparison.md) | 80 | 100 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c7393d7-8946-4cb4-8aca-a32dc7cf06dd) | [:white_check_mark:](# "Successfully processed") |
| [globalization/localizability/images-and-icons.md](https://github.com/MicrosoftDocs/globalization/blob/76c085cb7b1f3982dc90259f00df0f9fed8dea51/globalization%2Flocalizability%2Fimages-and-icons.md) | 77 | 100 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1622d67-d49d-4bf0-a05f-d1661191c029) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/internationalization/international-laws-and-standards.md](https://github.com/MicrosoftDocs/globalization/blob/590008b4eba0d628dc5341c0c670f564ed82068b/globalization%2Finternationalization%2Finternational-laws-and-standards.md) | 92 | 100 | 80 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cddf6fe2-6316-4991-bf47-f5afecf4cac8) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/other-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/590008b4eba0d628dc5341c0c670f564ed82068b/globalization%2Flocale%2Fother-locale-names.md) | 74 | 100 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1551c9f8-c630-406d-ba42-15660c391c00) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/sorting-and-string-comparison.md](https://github.com/MicrosoftDocs/globalization/blob/590008b4eba0d628dc5341c0c670f564ed82068b/globalization%2Flocale%2Fsorting-and-string-comparison.md) | 80 | 100 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d7e824a-4266-41cb-b443-e405f6a7849c) | [:white_check_mark:](# "Successfully processed") |
| [globalization/localizability/images-and-icons.md](https://github.com/MicrosoftDocs/globalization/blob/590008b4eba0d628dc5341c0c670f564ed82068b/globalization%2Flocalizability%2Fimages-and-icons.md) | 77 | 100 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8adbdd4c-f59f-4be6-a3f8-a220e0137ab2) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Review by jowilco — APPROVED** [review]

**Pull request merged**
