### PR TITLE
Update addresses.md

### PR DESCRIPTION
**Pull request by JnHs**
Fixes PoliCheck issue https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109078

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/locale/addresses.md](https://github.com/MicrosoftDocs/globalization/blob/612b8f51dead2c6dde99e1422ac8f2ace48011ca/globalization%2Flocale%2Faddresses.md) | 74 | 100 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b70658c-359f-4360-9243-872a84006131) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by JnHs** [comment]
#sign-off

**Comment by JnHs** [comment]
#sign-off

**Comment by JnHs** [comment]
@jowilco Another PoliCheck fix, hope you can merge this or let me know if any concerns. Thank you!

**Review by jowilco — APPROVED** [review]

**Comment by jowilco** [comment]
@JnHs Done.

**Pull request merged**
