### PR TITLE
Policheck Update - June 27 | Bulk Update

### PR DESCRIPTION
**Pull request by damabe**
Fixes the following Policheck issues:

https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109052
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109054
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109060
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109063
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109064
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109069
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109078
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109079
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109080
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109082
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109086
https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/109088

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/locale/fallback.md](https://github.com/MicrosoftDocs/globalization/blob/56c66ffd946db162aa41da30d6ec8447904a78ff/globalization%2Flocale%2Ffallback.md) | 74 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95f180ca-9470-4296-936a-3e9a17133fea) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/other-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/56c66ffd946db162aa41da30d6ec8447904a78ff/globalization%2Flocale%2Fother-locale-names.md) | 74 | 100 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1467aa80-6ab2-4bbb-a318-bc30a2facef1) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/standard-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/56c66ffd946db162aa41da30d6ec8447904a78ff/globalization%2Flocale%2Fstandard-locale-names.md) | 57 | 79 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9938d48f-e95d-45c6-b454-cf5559abdfe6) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/telephone-number.md](https://github.com/MicrosoftDocs/globalization/blob/56c66ffd946db162aa41da30d6ec8447904a78ff/globalization%2Flocale%2Ftelephone-number.md) | 66 | 100 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40a017cb-ad69-4841-9a44-18252fd739db) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/typing-settings.md](https://github.com/MicrosoftDocs/globalization/blob/56c66ffd946db162aa41da30d6ec8447904a78ff/globalization%2Flocale%2Ftyping-settings.md) | 78 | 100 | 73 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ada45422-676f-49a1-9327-9b1361a570c8) | [:white_check_mark:](# "Successfully processed") |
| [globalization/localizability/images-and-icons.md](https://github.com/MicrosoftDocs/globalization/blob/56c66ffd946db162aa41da30d6ec8447904a78ff/globalization%2Flocalizability%2Fimages-and-icons.md) | 77 | 100 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3db31434-d133-4d09-b35e-7281264fc638) | [:white_check_mark:](# "Successfully processed") |
| [globalization/testing/linguistic-validation.md](https://github.com/MicrosoftDocs/globalization/blob/56c66ffd946db162aa41da30d6ec8447904a78ff/globalization%2Ftesting%2Flinguistic-validation.md) | 95 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca8857df-da79-4c97-89bb-7655615c5dd9) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by damabe** [comment]
#sign-off This is a bulk update.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/locale/fallback.md](https://github.com/MicrosoftDocs/globalization/blob/253c9c65130bb0f925f004cf19f59cd66caead6c/globalization%2Flocale%2Ffallback.md) | 74 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e43ef85-8ea6-4287-8136-ed4febc999b1) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/other-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/253c9c65130bb0f925f004cf19f59cd66caead6c/globalization%2Flocale%2Fother-locale-names.md) | 74 | 100 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79d3b750-ef42-43dc-8329-ef869160c21e) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/telephone-number.md](https://github.com/MicrosoftDocs/globalization/blob/253c9c65130bb0f925f004cf19f59cd66caead6c/globalization%2Flocale%2Ftelephone-number.md) | 66 | 100 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9e68673-a878-42ba-9930-3423359a3e7f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/typing-settings.md](https://github.com/MicrosoftDocs/globalization/blob/253c9c65130bb0f925f004cf19f59cd66caead6c/globalization%2Flocale%2Ftyping-settings.md) | 78 | 100 | 73 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0a064ed-69d9-4bb5-9535-9872d12a8d1f) | [:white_check_mark:](# "Successfully processed") |
| [globalization/localizability/images-and-icons.md](https://github.com/MicrosoftDocs/globalization/blob/253c9c65130bb0f925f004cf19f59cd66caead6c/globalization%2Flocalizability%2Fimages-and-icons.md) | 77 | 100 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7570f07-f132-4462-9662-2e6aeab23fdf) | [:white_check_mark:](# "Successfully processed") |
| [globalization/testing/linguistic-validation.md](https://github.com/MicrosoftDocs/globalization/blob/253c9c65130bb0f925f004cf19f59cd66caead6c/globalization%2Ftesting%2Flinguistic-validation.md) | 95 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/823b808b-1635-42d7-99ec-c08cade96391) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology.

| Article | Acrolinx<br>score | Word and<br>Phrases Score | Correctness<br>Score | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [globalization/locale/fallback.md](https://github.com/MicrosoftDocs/globalization/blob/4026b80c84fc87ce5441846b08194c3f836c7439/globalization%2Flocale%2Ffallback.md) | 74 | 100 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6cf02941-25c7-4df4-8732-94ce0f72e36b) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/other-locale-names.md](https://github.com/MicrosoftDocs/globalization/blob/4026b80c84fc87ce5441846b08194c3f836c7439/globalization%2Flocale%2Fother-locale-names.md) | 74 | 100 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9422233-9fbd-455c-ac09-c55ad051e5d8) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/telephone-number.md](https://github.com/MicrosoftDocs/globalization/blob/4026b80c84fc87ce5441846b08194c3f836c7439/globalization%2Flocale%2Ftelephone-number.md) | 66 | 100 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d6314fc-f635-4992-a2ac-8c71b5c8730c) | [:white_check_mark:](# "Successfully processed") |
| [globalization/locale/typing-settings.md](https://github.com/MicrosoftDocs/globalization/blob/4026b80c84fc87ce5441846b08194c3f836c7439/globalization%2Flocale%2Ftyping-settings.md) | 79 | 100 | 74 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a46a9f94-0542-4ce2-850b-2f8d4e8a5993) | [:white_check_mark:](# "Successfully processed") |
| [globalization/testing/linguistic-validation.md](https://github.com/MicrosoftDocs/globalization/blob/4026b80c84fc87ce5441846b08194c3f836c7439/globalization%2Ftesting%2Flinguistic-validation.md) | 95 | 100 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a77c8877-cae6-4ae9-96c4-39448db80198) | [:white_check_mark:](# "Successfully processed") |

**More information about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/help/contribute/contribute-acrolinx-vscode)
- [False positives or issues](https://aka.ms/acrolinxbug)
- [Troubleshooting issues with Acrolinx](https://review.docs.microsoft.com/help/contribute/acrolinx-error-messages)

**Review by jowilco — APPROVED** [review]

**Pull request merged**
